Repository jfrog/jfrog-vscode-extension, pull requests merged in 2022-08, with the labels that each got.

#194 Stop auto-connecting upon pressing disconnect
  package.json
  src/main/commands/commandManager.ts
  src/main/connect/connectionManager.ts
  src/main/constants/contextKeys.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesDataProvider.ts
  src/main/treeDataProviders/dependenciesTree/treeDataProviderManager.ts
  src/main/treeDataProviders/treesManager.ts
  src/main/utils/scanUtils.ts
Labels: bug

#199 Display 'disconnected' status for new users
  src/main/connect/connectionManager.ts
Labels: ignore for release

#198 Add a pop-up hint in case of a scan failure
  src/main/commands/commandManager.ts
  src/main/log/logManager.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
  src/main/utils/goUtils.ts
  src/main/utils/mavenUtils.ts
  src/main/utils/nugetUtils.ts
Labels: improvement

#202 Improve tests
  src/test/tests/connectionManager.test.ts
  src/test/tests/scanLogic.test.ts
Labels: ignore for release

#205 Remove status bar duplication and change icon positions
  package.json
  src/main/commands/commandManager.ts
  src/main/connect/connectionManager.ts
Labels: bug
