Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-12, with the labels that each got.

#451 Update webview version to 0.2.12
  package-lock.json
  package.json
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/treeDataProviders/utils/yarnImpactGraph.ts
  src/test/tests/dependencyUtils.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
  src/test/tests/yarnImpactGraph.test.ts
Labels: improvement

#453 Analyzer manager version update to 1.6.0
  src/main/scanLogic/scanRunners/analyzerManager.ts
Labels: improvement

#454 Add verification code to the SSO login view
  package-lock.json
  package.json
  src/main/connect/connectionManager.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
  src/main/webview/event/tasks/login.ts
  src/test/tests/connectionManager.test.ts
  src/test/tests/yarnImpactGraph.test.ts
Labels: improvement

#450 applicabilityScan: add "indirect-cve-whitelist" to scanner YAML confi…
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/utils/utils.ts
  src/test/resources/applicableScan/npm/expectedScanResponse.json
  src/test/resources/applicableScan/python/expectedScanResponse.json
  src/test/resources/applicableScan/requestMultipleRoots.yaml
  src/test/resources/applicableScan/requestOneRoot.yaml
  src/test/tests/applicabilityScan.test.ts
  src/test/tests/integration/applicability.test.ts
Labels: improvement

#452 Make sure the webview is loaded before sending requests
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/webview/event/eventManager.ts
  src/main/webview/event/eventSender.ts
  src/main/webview/webviewSidebar.ts
  src/main/webview/webviewTab.ts
  src/test/tests/integration/applicability.test.ts
  src/test/tests/webview/event/eventManager.test.ts
Labels: bug

#458 Fix format & Update settings.json
  .vscode/settings.json
  src/main/utils/utils.ts
Labels: ignore for release
