Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-01, with the labels that each got.

#223 Adding applicablity scanning and bug fixes
  package-lock.json
  package.json
  resources/critical.png
  resources/high.png
  resources/low.png
  resources/medium.png
  resources/unknown.png
  src/extension.ts
  src/main/cache/issuesCache.ts
  src/main/commands/commandManager.ts
  src/main/diagnostics/abstractFileActionProvider.ts
  src/main/diagnostics/applicablityActionProvider.ts
  src/main/diagnostics/descriptorActionProvider.ts
  src/main/diagnostics/diagnosticsManager.ts
  src/main/scanLogic/scanGraphLogic.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/analyzerModels.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/eosScan.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/applicableTreeNode.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/codeFileTreeNode.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/codeIssueTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/licenseIssueTreeNode.ts
  src/main/treeDataProviders/issuesTree/fileTreeNode.ts
  src/main/treeDataProviders/issuesTree/issueTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/treesManager.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
  src/main/treeDataProviders/utils/stepProgress.ts
  src/main/types/projectType.ts
  src/main/types/severity.ts
  src/main/utils/cveApplicabilityRunner.ts
  src/main/utils/iconsPaths.ts
  src/main/utils/mavenUtils.ts
  src/main/utils/npmUtils.ts
  src/main/utils/resource.ts
  src/main/utils/scanUtils.ts
  src/main/utils/translators.ts
  src/test/tests/cveApplicabilityRunner.test.ts
Labels: new feature

#227 Adding exe ending for applicability binary in windows
  src/main/cache/issuesCache.ts
  src/main/diagnostics/descriptorActionProvider.ts
  src/main/log/logManager.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
  src/main/types/issuesData.ts
  src/main/utils/goUtils.ts
  src/main/utils/mavenUtils.ts
  src/main/utils/nugetUtils.ts
Labels: bug

#228 Show reason in webview, format scanner path response and fix opening in column view
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
  src/main/treeDataProviders/issuesTree/fileTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
  src/main/treeDataProviders/utils/stepProgress.ts
  src/main/types/projectType.ts
  src/main/utils/scanUtils.ts
  src/main/webviews/detailsWebView.ts
Labels: bug

#229 Fix tests
  src/main/utils/resource.ts
  src/test/tests/connectionManager.test.ts
  src/test/tests/goUtils.test.ts
  src/test/tests/resource.test.ts
  src/test/tests/translators.test.ts
Labels: bug

#231 Fix file opening on scan end
  src/main/diagnostics/descriptorActionProvider.ts
  src/main/diagnostics/diagnosticsManager.ts
  src/main/log/logManager.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
Labels: bug

#232 Adding tests for FileTreeNode
  src/main/treeDataProviders/issuesTree/fileTreeNode.ts
  src/test/tests/fileTreeNode.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
Labels: ignore for release

#236 Fix infected and fixed versions display for cve issues
  src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
Labels: bug

#238 Build impact path per component and issue
  src/main/treeDataProviders/utils/descriptorUtils.ts
Labels: bug

#239 Add ignore rules to violations
  package.json
  src/main/commands/commandManager.ts
  src/main/constants/contextKeys.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/licenseIssueTreeNode.ts
Labels: new feature

#237 Add root issues node tests
  package.json
  src/main/scanLogic/scanManager.ts
  src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/utils/configuration.ts
  src/test/tests/fileTreeNode.test.ts
  src/test/tests/issuesTreeNode.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
Labels: ignore for release

#241 Add gutter icons for applicable issues in editor
  src/main/diagnostics/applicabilityActionProvider.ts
Labels: improvement

#243 Descriptor sub tree tests
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
  src/test/tests/descriptorTree.test.ts
  src/test/tests/export.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
Labels: ignore for release

#244 Add go version as direct dependency for scan
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
  src/main/utils/goUtils.ts
  src/test/tests/goUtils.test.ts
Labels: improvement

#250 Upgrade webview to 0.1.18
  package-lock.json
  package.json
  src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/licenseIssueTreeNode.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
  src/main/types/issuesData.ts
Labels: improvement

#245 Add code action jump from dependency in editor to tree
  src/main/diagnostics/abstractFileActionProvider.ts
  src/main/diagnostics/applicabilityActionProvider.ts
  src/main/diagnostics/descriptorActionProvider.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
  src/main/utils/goUtils.ts
  src/main/utils/mavenUtils.ts
  src/main/utils/npmUtils.ts
  src/main/utils/pypiUtils.ts
  src/main/utils/yarnUtils.ts
  src/test/tests/descriptorTree.test.ts
  src/test/tests/goUtils.test.ts
  src/test/tests/maven.test.ts
  src/test/tests/npmUtils.test.ts
  src/test/tests/pypiUtils.test.ts
  src/test/tests/yarnUtils.test.ts
Labels: improvement

#246 Add jump from dependency in tree to location in editor
  src/main/diagnostics/descriptorActionProvider.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/descriptorUtils.ts
  src/test/tests/utils/treeNodeUtils.test.ts
Labels: improvement

#248 Add not applicable icon for each severity
  resources/Not_Applicable.svg
  resources/notApplicableCritical.svg
  resources/notApplicableHigh.svg
  resources/notApplicableLow.svg
  resources/notApplicableMedium.svg
  resources/notApplicableUnknown.svg
  src/main/types/severity.ts
  src/main/utils/iconsPaths.ts
Labels: improvement

#255 Refactor ApplicabilityActionProvider
  src/main/diagnostics/abstractFileActionProvider.ts
  src/main/diagnostics/applicabilityActionProvider.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/codeFileTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/test/tests/issuesTreeNode.test.ts
Labels: ignore for release

#251 Add EOS scan
  package-lock.json
  package.json
  src/main/commands/commandManager.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/analyzerModels.ts
  src/main/scanLogic/scanRunners/eosScan.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/codeIssueTreeNode.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/eosTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/utils.ts
  src/main/types/issuesData.ts
  src/main/utils/translators.ts
  src/main/webviews/detailsWebView.ts
Labels: new feature

#252 Remove not applicable mark for indirect dependency
  src/main/diagnostics/applicabilityActionProvider.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/descriptorTreeNode.ts
  src/main/treeDataProviders/issuesTree/fileTreeNode.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/test/tests/descriptorTree.test.ts
  src/test/tests/fileTreeNode.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
Labels: bug

#254 Fix command palette content
  package-lock.json
  package.json
  src/main/constants/contextKeys.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
  src/main/treeDataProviders/issuesTree/fileTreeNode.ts
  src/main/treeDataProviders/issuesTree/issueTreeNode.ts
Labels: bug

#257 Fix gutter icons for editors
  resources/notApplicableCritical.svg
  resources/notApplicableHigh.svg
  resources/notApplicableLow.svg
  resources/notApplicableMedium.svg
  resources/notApplicableUnknown.svg
  src/main/diagnostics/descriptorActionProvider.ts
Labels: bug

#259 Remove unused open file command def
  package.json
Labels: bug

#253 Add analyzer manager wrapper for scanners
  src/main/connect/connectionUtils.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/eosScan.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/utils/configuration.ts
  src/main/utils/scanUtils.ts
Labels: ignore for release

#264 Remove analyzer manager env variables log
  src/main/scanLogic/scanRunners/binaryRunner.ts
Labels: ignore for release
