Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-09, with the labels that each got.

#402 Wait before loading a page at the first time
  .github/workflows/test.yml
  src/main/webview/webviewManager.ts
  src/main/webview/webviewTab.ts
Labels: bug

#403 Add a new command for deleting caches
  package.json
  src/main/cache/cacheManager.ts
  src/main/commands/commandManager.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/treesManager.ts
Labels: new feature

#404 Upgrade the webview to the latest UI
  package-lock.json
  package.json
Labels: improvement

#407 Upgrade AM 1.3.2.2005632 - Add new SAST scanner
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/eosScan.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/eosTreeNode.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/utils/translators.ts
  src/test/resources/secretsScan/analyzerResponse.json
  src/test/resources/secretsScan/expectedScanResponse.json
  src/test/tests/integration/applicability.test.ts
  src/test/tests/scanAnlayzerRunner.test.ts
Labels: new feature

#409 Yarn - Fix incorrect package type
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
Labels: bug

#411 Applicability scanner scans the venv parent dir
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
Labels: bug

#410 Yarn - Fix incorrect impact graph
  src/main/scanLogic/scanGraphLogic.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/mavenTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/nugetTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/pypiTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesTreeNode.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/treeDataProviders/utils/yarnImpactGraph.ts
  src/main/types/projectDetails.ts
  src/main/utils/yarnUtils.ts
  src/test/tests/dependencyUtils.test.ts
  src/test/tests/goUtils.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
  src/test/tests/yarnImpactGraph.test.ts
Labels: bug

#412 Add Feedback button
  package.json
  src/main/commands/commandManager.ts
  src/main/utils/utils.ts
Labels: new feature

#414 Add SAST docs to README.md
  README.md
  resources/readme/preview/sast.png
Labels: ignore for release
