Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-11, with the labels that each got.

#435 Update GHA python tests
  src/test/resources/python/regex/setupAllKindOfDepsVariations.py
  src/test/resources/python/regex/setupWithNoName.py
  src/test/resources/python/requirements/requirements.txt
  src/test/resources/python/setup/setup.py
  src/test/resources/python/setupAndRequirements/requirements.txt
  src/test/resources/python/updateToFixedVersion/requirements.txt
  src/test/tests/pypiUtils.test.ts
Labels: ignore for release

#433 Change SAST log messages and update config default root
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/jasRunner.ts
  src/main/scanLogic/scanRunners/sastScan.ts
  src/main/utils/jfrogAppsConfig/jfrogAppsConfig.ts
  src/test/tests/appsConfig.test.ts
  src/test/tests/iacScan.test.ts
  src/test/tests/integration/iac.test.ts
  src/test/tests/integration/secrets.test.ts
  src/test/tests/sastScan.test.ts
  src/test/tests/scanAnlayzerRunner.test.ts
  src/test/tests/secretsScan.test.ts
Labels: ignore for release

#434 Go - Support projects with embed files
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
  src/main/utils/goUtils.ts
  src/test/resources/go/embedProject/go.mod
  src/test/resources/go/embedProject/main.go
  src/test/resources/go/embedProject/version.txt
  src/test/resources/go/prepareProjectWorkspace/.vscode/b
  src/test/resources/go/prepareProjectWorkspace/testdata/d
  src/test/resources/go/project2/go.sum
  src/test/tests/goUtils.test.ts
Labels: bug

#437 Enable Download of External Resources from Artifactory Remote Repository
  README.md
  package.json
  resources/readme/preview/externalResourcesRepository.png
  src/main/connect/connectionManager.ts
  src/main/connect/connectionUtils.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/iacScan.ts
  src/main/scanLogic/scanRunners/jasRunner.ts
  src/main/scanLogic/scanRunners/sastScan.ts
  src/main/scanLogic/scanRunners/secretsScan.ts
  src/main/scanLogic/sourceCodeScan/jasRunnerFactory.ts
  src/main/scanLogic/sourceCodeScan/supportedScans.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/utils/configuration.ts
  src/main/utils/resource.ts
  src/main/utils/usageUtils.ts
  src/test/tests/applicabilityScan.test.ts
  src/test/tests/externalResourcesRepository.test.ts
  src/test/tests/iacScan.test.ts
  src/test/tests/integration/applicability.test.ts
  src/test/tests/integration/externalResourcesRepository.test.ts
  src/test/tests/integration/iac.test.ts
  src/test/tests/integration/secrets.test.ts
  src/test/tests/issuesTreeDataProvider.test.ts
  src/test/tests/resource.test.ts
  src/test/tests/sastScan.test.ts
  src/test/tests/scanAnlayzerRunner.test.ts
  src/test/tests/secretsScan.test.ts
  src/test/tests/usageUtils.test.ts
  src/test/tests/utils/MockJasRunnerFactory.ts
  src/test/tests/utils/testIntegration.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
  src/test/tests/utils/utils.test.ts
Labels: new feature

#438 Update nuget-deps-tree dependency to 0.3.1
  package-lock.json
  package.json
Labels: improvement

#441 Add .git to default exclusions
  package.json
Labels: improvement

#442 Go - Scan dependencies vulnerabilities for test data
  src/main/utils/goUtils.ts
  src/test/resources/go/prepareProjectWorkspace/testdata/d
Labels: improvement

#443 Fix source code format
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/test/tests/integration/externalResourcesRepository.test.ts
Labels: ignore for release

#445 Move the docs to the new documentation site
  README.md
  resources/Applicable.svg
  resources/Expand.svg
  resources/Normal.png
  resources/Research.svg
  resources/connect.png
  resources/extensionIcon.png
  resources/readme/filter.png
  resources/readme/gifs/ci.gif
  resources/readme/gifs/logs.gif
  resources/readme/preview/contextualDetails.png
  resources/readme/preview/externalResourcesRepository.png
  resources/readme/preview/iac.png
  resources/readme/preview/ignoreRule.png
  resources/readme/preview/impactGraph.png
  resources/readme/preview/install.png
  resources/readme/preview/jfrogTab.png
  resources/readme/preview/openSettings.png
  resources/readme/preview/publicDetails.png
  resources/readme/preview/refresh.png
  resources/readme/preview/research.png
  resources/readme/preview/sast.png
  resources/readme/preview/secrets.png
  resources/readme/preview/sighInPage.png
  resources/readme/preview/sighInPageEnvVar.png
  resources/readme/preview/sighInPageJFrogCli.png
  resources/readme/preview/ssoButton.png
  resources/readme/preview/treeView.png
  resources/readme/preview/updateQuickFix.png
  resources/readme/refresh.png
  resources/readme/severities/Critical.png
  resources/readme/severities/High.png
  resources/readme/severities/Low.png
  resources/readme/severities/Medium.png
  resources/readme/severities/Unknown.png
  resources/readme/severities/notApplicableCritical.png
  resources/readme/severities/notApplicableHigh.png
  resources/readme/severities/notApplicableLow.png
  resources/readme/severities/notApplicableMedium.png
  resources/readme/severities/notApplicableUnknown.png
  resources/severities/Critical.svg
  resources/severities/High.svg
  resources/severities/Low.svg
  resources/severities/Medium.svg
  resources/severities/Unknown.svg
  resources/severities/hover/criticalHover.png
  resources/severities/hover/highHover.png
  resources/severities/hover/lowHover.png
  resources/severities/hover/mediumHover.png
  resources/severities/hover/unknownHover.png
  resources/severities/notApplicableCritical.svg
  resources/severities/notApplicableHigh.svg
  resources/severities/notApplicableLow.svg
  resources/severities/notApplicableMedium.svg
  resources/severities/notApplicableUnknown.svg
  resources/violatedLicense.png
Labels: ignore for release

#447 Replace an emoji in the README
  README.md
Labels: ignore for release

#449 Use the platform specific path for JFrog config
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/jasRunner.ts
  src/main/scanLogic/sourceCodeScan/jasRunnerFactory.ts
  src/test/tests/integration/JasRunnerFactory.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
Labels: bug

#444 Remove timeout from advanced security scan
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/iacScan.ts
  src/main/scanLogic/scanRunners/jasRunner.ts
  src/main/scanLogic/scanRunners/sastScan.ts
  src/main/scanLogic/scanRunners/secretsScan.ts
  src/main/utils/resource.ts
  src/main/utils/runUtils.ts
  src/main/utils/scanUtils.ts
  src/test/tests/runUtils.test.ts
  src/test/tests/scanAnlayzerRunner.test.ts
  src/test/tests/scanUtils.test.ts
Labels: improvement
