Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-03, with the labels that each got.

#293 Add min version and severity icons to readme
  README.md
  resources/connect.png
  resources/package/npm.png
  resources/package/pypi.png
  resources/readme/severities/Critical.png
  resources/readme/severities/High.png
  resources/readme/severities/Low.png
  resources/readme/severities/Medium.png
  resources/readme/severities/Unknown.png
  resources/readme/severities/notApplicableCritical.png
  resources/readme/severities/notApplicableHigh.png
  resources/readme/severities/notApplicableLow.png
  resources/readme/severities/notApplicableMedium.png
  resources/readme/severities/notApplicableUnknown.png
  resources/severities/Critical.svg
  resources/severities/High.svg
  resources/severities/Low.svg
  resources/severities/Medium.svg
  resources/severities/Unknown.svg
  resources/severities/hover/criticalHover.png
  resources/severities/hover/highHover.png
  resources/severities/hover/lowHover.png
  resources/severities/hover/mediumHover.png
  resources/severities/hover/unknownHover.png
  resources/severities/normal.png
  resources/severities/notApplicableCritical.svg
  resources/severities/notApplicableHigh.svg
  resources/severities/notApplicableLow.svg
  resources/severities/notApplicableMedium.svg
  resources/severities/notApplicableUnknown.svg
  src/main/utils/iconsPaths.ts
Labels: ignore for release

#295 Add tests to translators for webview and analyzer
  src/test/tests/translators.test.ts
Labels: ignore for release

#296 Remove scan from cache if week passed
  README.md
  resources/Normal.png
  src/main/cache/issuesCache.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/projectDependencyTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/treesManager.ts
  src/main/types/workspaceIssuesDetails.ts
  src/main/utils/iconsPaths.ts
  src/main/utils/utils.ts
Labels: improvement

#294 Refactor descriptor scans and build trees async per package
  src/extension.ts
  src/main/cache/cacheManager.ts
  src/main/cache/issuesCache.ts
  src/main/filter/filterManager.ts
  src/main/scanLogic/scanGraphLogic.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/treeDataProviders/ciTree/buildsDataProvider.ts
  src/main/treeDataProviders/ciTree/buildsTree.ts
  src/main/treeDataProviders/ciTree/ciTitleNode.ts
  src/main/treeDataProviders/ciTree/dependencyDetailsProvider.ts
  src/main/treeDataProviders/ciTree/generalDetailsDataProvider.ts
  src/main/treeDataProviders/ciTree/issuesDataProvider.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/mavenTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/rootTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/virtualEnvPypiTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesTreeFactory.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/treesManager.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/treeDataProviders/utils/stepProgress.ts
  src/main/types/workspaceIssuesDetails.ts
  src/main/utils/builds/buildsUtils.ts
  src/main/utils/builds/ciManager.ts
  src/main/utils/consts.ts
  src/main/utils/goUtils.ts
  src/main/utils/mavenUtils.ts
  src/main/utils/npmUtils.ts
  src/main/utils/nugetUtils.ts
  src/main/utils/pomTree.ts
  src/main/utils/pypiUtils.ts
  src/main/utils/scanUtils.ts
  src/main/utils/utils.ts
  src/main/utils/yarnUtils.ts
  src/test/tests/componentDetails.test.ts
  src/test/tests/fileTreeNode.test.ts
  src/test/tests/goUtils.test.ts
  src/test/tests/issuesDataProvider.test.ts
  src/test/tests/issuesTreeNode.test.ts
  src/test/tests/maven.test.ts
  src/test/tests/npmUtils.test.ts
  src/test/tests/nugetUtils.test.ts
  src/test/tests/pypiUtils.test.ts
  src/test/tests/yarnUtils.test.ts
Labels: improvement

#300 Only add protocol prefix if proxy is from config
  src/main/scanLogic/scanRunners/binaryRunner.ts
Labels: bug

#301 Update client js to 2.6.3
  package-lock.json
  package.json
Labels: ignore for release

#299 Clear oldest logs first when log directory is full
  src/main/log/logUtils.ts
Labels: bug

#297 Add dependency scan tests and data population
  package-lock.json
  src/main/scanLogic/scanGraphLogic.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/test/resources/scanResponses/scanGraphViolations.json
  src/test/resources/scanResponses/scanGraphVulnerabilities.json
  src/test/tests/cveApplicabilityTree.test.ts
  src/test/tests/dependencyUtils.test.ts
  src/test/tests/descriptorUtils.test.ts
  src/test/tests/fileTreeNode.test.ts
  src/test/tests/issuesTreeNode.test.ts
  src/test/tests/scanGraphLogic.test.ts
  src/test/tests/scanLogic.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
Labels: ignore for release

#302 Add button to open the extension settings
  README.md
  package.json
  resources/readme/preview/openSettings.png
  src/main/commands/commandManager.ts
  src/main/utils/utils.ts
Labels: new feature

#304 Add option to select connection method
  README.md
  resources/readme/preview/connect.png
  src/main/commands/commandManager.ts
  src/main/connect/connectionManager.ts
Labels: improvement

#310 Documentation improvements
  README.md
Labels: ignore for release

#308 Add timeout to analyzer scans
  package-lock.json
  package.json
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/eosScan.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/treeDataProviders/utils/stepProgress.ts
  src/main/utils/runUtils.ts
  src/main/utils/scanUtils.ts
  src/test/tests/runUtils.test.ts
Labels: improvement

#311 Remove constant maven version for tests
  .github/workflows/test.yml
Labels: ignore for release

#316 Use npm ci and update Actions
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pull-request.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .jfrog-pipelines/snapshot.yml
Labels: ignore for release

#313 Add the option to skip npm dev dependencies
  .github/workflows/test.yml
  package.json
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/yarnTree.ts
  src/main/utils/cmds/npm.ts
  src/main/utils/configuration.ts
  src/main/utils/npmUtils.ts
  src/main/utils/yarnUtils.ts
  src/test/resources/npm/filterDevDepsTest/package-lock.json
  src/test/resources/npm/filterDevDepsTest/package.json
  src/test/resources/npm/utilsTest/project-1/package-lock.json
  src/test/resources/npm/utilsTest/project-1/package.json
  src/test/resources/npm/utilsTest/project-2/package-lock.json
  src/test/resources/npm/utilsTest/project-2/package.json
  src/test/resources/npm/utilsTest/project-3/package-lock.json
  src/test/resources/npm/utilsTest/project-3/package.json
  src/test/tests/filterNpmDependencies.test.ts
  src/test/tests/npmCmd.test.ts
  src/test/tests/npmUtils.test.ts
Labels: new feature

#312 Add general analyzer manager tests
  src/main/scanLogic/scanRunners/analyzerModels.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/eosScan.ts
  src/main/treeDataProviders/utils/stepProgress.ts
  src/main/utils/runUtils.ts
  src/test/tests/scanAnlayzerRunner.test.ts
Labels: ignore for release

#322 Fix typo in package.json
  package.json
Labels: ignore for release

#320 Update README.md
  README.md
Labels: ignore for release
