Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-07, with the labels that each got.

#363 Use a fixed version of the AnalyzerManager
  src/main/scanLogic/scanRunners/binaryRunner.ts
Labels: ignore for release

#368 Remove debug leftover
  src/test/tests/applicabilityScan.test.ts
Labels: ignore for release

#367 npm - Partial scan
  src/main/treeDataProviders/dependenciesTree/dependenciesRoot/npmTree.ts
  src/main/utils/cmds/npm.ts
  src/test/resources/npm/partialTree/package-lock.json
  src/test/resources/npm/partialTree/package.json
  src/test/tests/npmUtils.test.ts
Labels: improvement

#373 Fix - Download AnalyzerManager async issue
  src/main/scanLogic/scanManager.ts
  src/main/utils/resource.ts
  src/main/utils/utils.ts
Labels: bug

#376 Add ApplicabilityScan for Maven
  src/main/scanLogic/scanRunners/applicabilityScan.ts
Labels: improvement

#375 Scan Applicable issues per workspace and not per descriptor
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/utils/scanUtils.ts
  src/main/utils/utils.ts
  src/test/tests/applicabilityScan.test.ts
  src/test/tests/dependencyUtils.test.ts
Labels: bug

#377 Close old web view page on refresh
  src/main/commands/commandManager.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/webview/webview.ts
Labels: improvement

#379 Update README.md
  README.md
Labels: ignore for release

#382 Apply uppercase log level in AnalyzerManager
  src/main/utils/translators.ts
  src/test/tests/translators.test.ts
Labels: bug

#386 Add warning in case os not supported the scanners
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/utils/scanUtils.ts
  src/main/utils/translators.ts
  src/test/tests/scanAnlayzerRunner.test.ts
Labels: ignore for release

#385 Block exclusion pattern empty after comma
  package.json
Labels: bug

#384 Add scanners logs to integration tests
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/eosScan.ts
  src/main/scanLogic/scanRunners/iacScan.ts
  src/main/scanLogic/scanRunners/secretsScan.ts
  src/test/tests/integration/applicability.test.ts
  src/test/tests/integration/iac.test.ts
  src/test/tests/integration/secrets.test.ts
  src/test/tests/scanAnlayzerRunner.test.ts
Labels: ignore for release

#387 Add SVG detection on README.md
  .github/workflows/detect-svg-in-readme.yml
  README.md
Labels: ignore for release
