Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-05, with the labels that each got.

#339 Add Infrastructure As Code (Iac) advance scan
  README.md
  src/main/cache/issuesCache.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/analyzerModels.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/iacScan.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/iacTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesRootTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/types/workspaceIssuesDetails.ts
  src/main/utils/scanUtils.ts
  src/main/utils/translators.ts
  src/test/resources/iacScan/analyzerResponse.json
  src/test/resources/iacScan/expectedScanResponse.json
  src/test/resources/iacScan/req_sw_terraform_aws_cloudfront_tls_only.tf
  src/test/resources/iacScan/req_sw_terraform_aws_cloudtrail_encrypt.tf
  src/test/tests/analyzerUtils.test.ts
  src/test/tests/applicabilityScan.test.ts
  src/test/tests/iacScan.test.ts
  src/test/tests/integration/iacIntegration.test.ts
  src/test/tests/translators.test.ts
  src/test/tests/utils/testIntegration.test.ts
  src/test/tests/utils/treeNodeUtils.test.ts
  src/test/tests/utils/utils.test.ts
Labels: new feature

#342 Notify before delete cache once a week
  package.json
  src/main/cache/issuesCache.ts
  src/main/codeLens/abstractCodeLensProvider.ts
  src/main/commands/commandManager.ts
Labels: improvement

#345 Fix Windows tests for parsing path
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/test/tests/analyzerUtils.test.ts
Labels: ignore for release

#346 Webview - Add message passing from the webview to the IDE
  package-lock.json
  package.json
  src/extension.ts
  src/main/commands/commandManager.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/eosTreeNode.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/iacTreeNode.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/secretsTreeNode.ts
  src/main/utils/translators.ts
  src/main/webview/eventManager.ts
  src/main/webview/webview.ts
  src/main/webviews/detailsWebView.ts
Labels: new feature

#350 Update Frogbot scan and fix workflow
  .github/workflows/frogbot-scan-and-fix.yml
  README.md
Labels: ignore for release

#352 Remove info log when scan not supported
  src/main/utils/scanUtils.ts
Labels: bug

#353 Fix run for whitespace in path of MavenReader
  src/main/utils/mavenUtils.ts
Labels: bug
