Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-08, with the labels that each got.

#390 Vulnerability Contextual Analysis - Add additional CVE findings
  src/main/scanLogic/scanRunners/binaryRunner.ts
Labels: improvement

#358 New login page
  THIRD_PARTY_NOTICES
  package-lock.json
  package.json
  resources/readme/connect.png
  src/extension.ts
  src/main/commands/commandManager.ts
  src/main/connect/connectionManager.ts
  src/main/connect/connectionUtils.ts
  src/main/constants/contextKeys.ts
  src/main/log/logManager.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/treesManager.ts
  src/main/webview/event/eventManager.ts
  src/main/webview/event/eventSender.ts
  src/main/webview/event/tasks/jumpToCode.ts
  src/main/webview/event/tasks/login.ts
  src/main/webview/eventManager.ts
  src/main/webview/webview.ts
  src/main/webview/webviewManager.ts
  src/main/webview/webviewSidebar.ts
  src/main/webview/webviewTab.ts
  src/test/tests/connectionManager.test.ts
  src/test/tests/webview/event/eventManager.test.ts
  src/test/tests/webview/event/eventSender.test.ts
  src/test/tests/webview/event/tasks/jumpToCode.test.ts
  src/test/tests/webview/mockWebview.test.ts
Labels: improvement

#364 Documentation updates for SSO Login support
  README.md
  resources/readme/preview/connect.png
  resources/readme/preview/jfrogTab.png
  resources/readme/preview/sighInPage.png
  resources/readme/preview/sighInPageEnvVar.png
  resources/readme/preview/sighInPageJFrogCli.png
  resources/readme/preview/ssoButton.png
Labels: ignore for release

#391 Update webview version
  package-lock.json
  package.json
Labels: ignore for release

#395 Update Analyzer Manager version to 1.2.4.1908731
  src/main/scanLogic/scanRunners/binaryRunner.ts
Labels: ignore for release

#392 Limit Impact Graph size
  package-lock.json
  package.json
  src/extension.ts
  src/main/cache/cacheManager.ts
  src/main/cache/cacheRecord.ts
  src/main/cache/issuesCache.ts
  src/main/cache/scanCacheManager.ts
  src/main/cache/scanCacheObject.ts
  src/main/diagnostics/descriptorActionProvider.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/cveTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/licenseIssueTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/types/workspaceIssuesDetails.ts
  src/main/utils/utils.ts
  src/main/webview/event/tasks/login.ts
  src/main/webview/webviewManager.ts
  src/test/tests/connectionManager.test.ts
  src/test/tests/dependencyUtils.test.ts
  src/test/tests/goUtils.test.ts
  src/test/tests/scanCacheManager.test.ts
Labels: improvement

#394 Contextual Analysis - Scan all CVEs for Python projects
  src/main/cache/cacheManager.ts
  src/main/cache/cacheRecord.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/treeDataProviders/utils/dependencyUtils.ts
  src/main/types/workspaceIssuesDetails.ts
  src/main/utils/pypiUtils.ts
  src/test/tests/applicabilityScan.test.ts
Labels: bug

#396 Documentation and in product messaging improvements
  README.md
  package.json
Labels: ignore for release

#398 Add suppression to secrets scan
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/main/scanLogic/scanRunners/secretsScan.ts
Labels: improvement

#399 Bump semver from 7.5.2 to 7.5.4
  package-lock.json
  package.json
Labels: ignore for release

#397 Documentation improvements
  README.md
Labels: ignore for release

#400 Fix scanning wrong directory in CA for venv
  src/main/treeDataProviders/utils/analyzerUtils.ts
Labels: bug
