Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-10, with the labels that each got.

#418 Add SAST to the welcome page
  README.md
  package.json
Labels: ignore for release

#422 Scale all icons to 16X16
  resources/dark/build.png
  resources/dark/ci.png
  resources/dark/filter.png
  resources/dark/refresh.png
  resources/light/build.png
  resources/light/ci.png
  resources/light/filter.png
  resources/light/refresh.png
Labels: bug

#421 Fix connection lost detection
  package.json
  src/main/connect/connectionManager.ts
  src/main/connect/connectionUtils.ts
  src/test/tests/connectionManager.test.ts
Labels: bug

#423 Update dependencies
  package-lock.json
Labels: improvement

#365 Maven - Update dependency versions in the properties section
  src/main/dependencyUpdate/mavenDependencyUpdate.ts
  src/main/diagnostics/codeFileActionProvider.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/dependencyIssuesTreeNode.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/projectDependencyTreeNode.ts
  src/main/treeDataProviders/issuesTree/fileTreeNode.ts
  src/main/utils/mavenUtils.ts
  src/test/resources/maven/treeTestsProjects/dependency/pom.xml
  src/test/resources/maven/treeTestsProjects/empty/pom.xml
  src/test/resources/maven/treeTestsProjects/multiPomDependency/multi1/pom.xml
  src/test/resources/maven/treeTestsProjects/multiPomDependency/multi2/pom.xml
  src/test/resources/maven/treeTestsProjects/multiPomDependency/multi3/pom.xml
  src/test/resources/maven/treeTestsProjects/multiPomDependency/pom.xml
  src/test/resources/maven/updateToFixVersionProjects/updateParentPomProperty/multi1/pom.xml
  src/test/resources/maven/updateToFixVersionProjects/updateParentPomProperty/pom.xml
  src/test/resources/maven/updateToFixVersionProjects/updatePom/pom.xml
  src/test/resources/maven/updateToFixVersionProjects/updatePomProperty/pom.xml
  src/test/tests/maven.test.ts
  src/test/tests/mavenUpdate.test.ts
Labels: improvement

#424 Update dependencies
  package-lock.json
  package.json
Labels: improvement
