Repository jfrog/jfrog-vscode-extension, pull requests merged in 2023-04, with the labels that each got.

#327 Simplify the Frogbot workflows & add badge
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pull-request.yml
  README.md
Labels: improvement

#325 Update test.yml
  .github/workflows/cla.yml
  .github/workflows/frogbot-scan-pull-request.yml
  .github/workflows/test.yml
Labels: ignore for release

#323 Add applicability scan tests
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/applicableTreeNode.ts
  src/test/resources/applicableScan/analyzerResponse.json
  src/test/resources/applicableScan/requestMultipleRoots.yaml
  src/test/resources/applicableScan/requestOneRoot.yaml
  src/test/resources/cveApplicability/project/bad.js
  src/test/resources/cveApplicability/project/package-lock.json
  src/test/resources/cveApplicability/project/package.json
  src/test/resources/scanResponses/graphScanViolations.json
  src/test/resources/scanResponses/graphScanVulnerabilities.json
  src/test/resources/scanResponses/summaryComponent.json
  src/test/tests/applicabilityScan.test.ts
  src/test/tests/utils/utils.test.ts
Labels: ignore for release

#332 Promote jfrog-client-js to version to 2.6.5
  package-lock.json
  package.json
Labels: ignore for release

#330 Add option to set timeout in settings
  package.json
  src/main/connect/connectionUtils.ts
  src/main/utils/configuration.ts
  src/test/tests/connectionManager.test.ts
  src/test/tests/utils/utils.test.ts
Labels: new feature

#331 Update Frogbot badge to PNG in README.md
  README.md
Labels: ignore for release

#334 Add a daily scan schedule for Frogbot
  .github/workflows/frogbot-scan-and-fix.yml
Labels: improvement

#338 Promote jfrog-ide-webview to version to 0.1.23
  package-lock.json
  package.json
Labels: ignore for release

#333 Add applicable integration test
  .github/workflows/removeLabel.yml
  .github/workflows/test.yml
  src/main/connect/connectionManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/scanRunners/binaryRunner.ts
  src/test/index.ts
  src/test/resources/applicableScan/npm/expectedScanResponse.json
  src/test/resources/applicableScan/npm/index.js
  src/test/resources/applicableScan/python/expectedScanResponse.json
  src/test/resources/applicableScan/python/main.py
  src/test/tests/integration/applicabilityIntegration.test.ts
  src/test/tests/utils/testIntegration.test.ts
Labels: improvement, safe to test

#340 Fix tests in Window Applicable integration
  .github/workflows/test.yml
  src/test/tests/connectionManager.test.ts
  src/test/tests/integration/applicabilityIntegration.test.ts
Labels: ignore for release

#335 Fix broken link - Setup free platform
  package.json
Labels: bug
