Repository jfrog/jfrog-vscode-extension, pull requests merged in 2024-11, with the labels that each got.

#500 Removed the "fix action" for indirect dependencies
  .jfrog/jfrog-apps-config.yml
  src/main/diagnostics/descriptorActionProvider.ts
Labels: bug

#496 token validation feature in ide
  package-lock.json
  package.json
  src/main/connect/connectionManager.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/main/scanLogic/scanRunners/analyzerModels.ts
  src/main/scanLogic/scanRunners/jasRunner.ts
  src/main/scanLogic/scanRunners/secretsScan.ts
  src/main/scanLogic/sourceCodeScan/supportedScans.ts
  src/main/treeDataProviders/issuesTree/codeFileTree/secretsTreeNode.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/main/types/tokenStatus.ts
  src/main/utils/configuration.ts
  src/test/resources/secretsScan/analyzerResponse.json
  src/test/resources/secretsScan/applicable_base64.js
  src/test/resources/secretsScan/expectedScanResponse.json
  src/test/tests/integration/secrets.test.ts
  src/test/tests/secretsScan.test.ts
  src/test/tests/utils/testAnalyzer.test.ts
  src/test/tests/utils/testIntegration.test.ts
Labels: new feature

#502 Upgraded am version to 1.11.2
  src/main/scanLogic/scanRunners/analyzerManager.ts
Labels: improvement

#504 update_am_1_11_7
  src/main/scanLogic/scanRunners/analyzerManager.ts
Labels: improvement

#505 Update am 1.11.8
  src/main/scanLogic/scanRunners/analyzerManager.ts
Labels: bug

#506 Update Webview v0.3.0
  package-lock.json
  package.json
  src/main/diagnostics/descriptorActionProvider.ts
  src/main/scanLogic/scanManager.ts
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/scanLogic/sourceCodeScan/supportedScans.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
Labels: improvement
