Repository jfrog/jfrog-vscode-extension, pull requests merged in 2024-07, with the labels that each got.

#478 Don't show applicable status if not covered
  src/main/scanLogic/scanRunners/applicabilityScan.ts
Labels: bug

#481 Add contribute page
  CONTRIBUTING.md
  README.md
Labels: ignore for release

#480 Remove node 14 tests
  .github/workflows/test.yml
Labels: ignore for release

#479 Use const AnalyzerManager version 1.8.3
  package.json
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/main/utils/configuration.ts
Labels: improvement

#484 Fix parsing Contextual Analysis statues in response
  src/main/scanLogic/scanRunners/analyzerModels.ts
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/test/resources/applicableScan/analyzerResponse.json
Labels: bug

#485 Update Analyzer Manager to v1.8.8
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/main/utils/utils.ts
Labels: improvement

#488 Update analyzer manager to v1.8.9
  .github/workflows/test.yml
  src/main/scanLogic/scanRunners/analyzerManager.ts
  src/test/tests/integration/applicability.test.ts
  src/test/tests/integration/secrets.test.ts
Labels: improvement

#486 change jfrog-ide-webview version to the latest 0.2.14
  package-lock.json
  package.json
  src/main/treeDataProviders/issuesTree/codeFileTree/sastTreeNode.ts
Labels: improvement
