Repository jfrog/jfrog-vscode-extension, pull requests merged in 2025-03, with the labels that each got.

#512 Support all Contextual-Analysis statuses
  package-lock.json
  package.json
  src/main/scanLogic/scanRunners/applicabilityScan.ts
  src/main/treeDataProviders/issuesTree/descriptorTree/projectDependencyTreeNode.ts
  src/main/treeDataProviders/issuesTree/issuesTreeDataProvider.ts
  src/main/treeDataProviders/utils/analyzerUtils.ts
  src/test/resources/applicableScan/npm/expectedScanResponse.json
  src/test/resources/applicableScan/python/expectedScanResponse.json
  src/test/tests/applicabilityScan.test.ts
  src/test/tests/integration/applicability.test.ts
  src/test/tests/translators.test.ts
Labels: improvement

#514 Added back package lock
  package-lock.json
Labels: ignore for release

#515 Fixed proxy configuration to retrieve the correct proxy details
  src/main/connect/connectionUtils.ts
Labels: bug

#516 Updated webview version
  package-lock.json
  package.json
Labels: dependencies

#517 Changed the SAST title
  src/main/scanLogic/scanRunners/analyzerModels.ts
  src/main/scanLogic/scanRunners/sastScan.ts
Labels: bug

#518 update am to 1.15.2
  src/main/scanLogic/scanRunners/analyzerManager.ts
Labels: improvement
